version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - reupen
  labels:
  - dependencies
  ignore:
  - dependency-name: pytest
    versions:
    - 6.2.2
  rebase-strategy: disabled
